# Generated by Django 4.0.6 on 2024-12-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_alter_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
