# Generated by Django 4.1.7 on 2025-01-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
